apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "harvester-node-manager.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harvester-node-manager.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "harvester-node-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "harvester-node-manager.selectorLabels" . | nindent 8 }}
        name: harvester-node-manager
    spec:
      serviceAccountName: {{ include "harvester-node-manager.name" . }}
      containers:
        - name: node-manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          command:
            - harvester-node-manager
          env:
            - name: NODENAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: HOST_PROC
              value: /host/proc
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /sys/kernel/mm/ksm
              name: ksm
              readOnly: false
            - mountPath: /host/proc
              name: proc
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: ksm
          hostPath:
            path: /sys/kernel/mm/ksm
        - name: proc
          hostPath:
            path: /proc