apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vspherexcopyvolumepopulators.forklift.konveyor.io
  annotations:
    controller-gen.kubebuilder.io/version: v0.17.0
  labels:
  {{- include "forklift-operator.labels" . | nindent 4 }}
spec:
  group: forklift.konveyor.io
  names:
    kind: VSphereXcopyVolumePopulator
    listKind: VSphereXcopyVolumePopulatorList
    plural: vspherexcopyvolumepopulators
    shortNames:
    - vxvp
    - vxvps
    singular: vspherexcopyvolumepopulator
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            properties:
              secretName:
                description: The secret name with vsphere and storage credentials
                type: string
              storageVendorProduct:
                description: |-
                  StorageVendorProduct is the storage vendor the target disk and PVC are connected to
                  Supported values [vantara, ontap, primera3par]
                type: string
              vmId:
                description: VmId is the VM object id in vSphere
                type: string
              vmdkPath:
                description: |-
                  VmdkPath is the full path the vmdk disk. A valid path format is
                  '[] /.vmdk'
                type: string
            required:
            - secretName
            - storageVendorProduct
            - vmId
            - vmdkPath
            type: object
          status:
            properties:
              progress:
                type: string
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
