apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "harvester-pcidevices-controller.labels" . | nindent 4 }}
  name:  {{ include "harvester-pcidevices-controller.serviceAccountName" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "harvester-pcidevices-controller.labels" . | nindent 4 }}
  name:  {{ include "harvester-pcidevices-controller.fullname" . }}
rules:
  - apiGroups: [ "apiextensions.k8s.io" ]
    resources: [ "customresourcedefinitions" ]
    verbs: [ "*" ]
  - apiGroups: [ "" ]
    resources: [ "nodes" ]
    verbs: [ "get", "watch", "list", "update" ]
  - apiGroups: [ "" ]
    resources: [ "configmaps", "events", "secrets"]
    verbs: [ "get", "watch", "list", "update", "create" ]
  - apiGroups: [ "" ]
    resources: [ "namespaces" ]
    verbs: [ "get", "watch", "list" ]
  - apiGroups: [ "devices.harvesterhci.io" ]
    resources: [ "*" ]
    verbs: [ "get", "watch", "list", "update", "create", "delete"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations", "validatingwebhookconfigurations"]
    verbs: [ "get", "watch", "list", "update", "create", "delete", "patch" ]
  - apiGroups: ["apiregistration.k8s.io"]
    resources: ["apiservices"]
    verbs: [ "get", "watch", "list", "update", "create", "delete" ]
  - apiGroups: ["kubevirt.io"]
    resources: ["kubevirts"]
    verbs: [ "get", "update" ]
  - apiGroups: ["kubevirt.io"]
    resources: ["virtualmachines"]
    verbs: [ "get", "list", "watch" ]    
  - apiGroups: ["network.harvesterhci.io"]
    resources: ["vlanconfigs"]
    verbs: [ "get", "list", "watch" ]      
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: [ "get", "list", "watch", "create", "update" ]
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "watch", "list" ]
  - apiGroups: [ "" ]
    resources: [ "pods/exec" ]
    verbs: [ "create" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "harvester-pcidevices-controller.labels" . | nindent 4 }}
  name: {{ include "harvester-pcidevices-controller.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "harvester-pcidevices-controller.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "harvester-pcidevices-controller.serviceAccountName" . }}
    namespace: harvester-system