# Default values for harvester-rbac.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

clusterRole:
  virtClusterManage:
    additionalRules:
      # - apiGroups: [""]
      #   resources: [""]
      #   verbs: [""]
  virtClusterView:
    additionalRules:
      # - apiGroups: [""]
      #   resources: [""]
      #   verbs: [""]

projectRole:
  virtProjectManage:
    additionalRules:
      # - apiGroups: [""]
      #   resources: [""]
      #   verbs: [""]
  virtProjectView:
    additionalRules:
      # - apiGroups: [""]
      #   resources: [""]
      #   verbs: [""]
